In [1]:
#EXP -5

In [2]:
#Aim:To create 1D,2D,and Multidimensional array

In [1]:
#Name:Pratik Pravin Thorat
#Roll no.:76
#Subject:ET1
#Sec:B
#Date:21/08/2025

In [2]:
import numpy as np

In [3]:
#creating 1D array using numpy

In [4]:
a1=np.array([10,20,30,40,50])

In [5]:
a1

array([10, 20, 30, 40, 50])

In [6]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [7]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [8]:
#creating 2D array using matrix

In [9]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
